apiVersion: v1
kind: Service
metadata:
  name: udagram-reverseproxy-pod
  labels:
    run: udagram-reverseproxy-pod
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: udagram-reverseproxy-pod